read pw
echo $pw | sudo -S nvidia-smi -lgc 690
echo $pw | sudo -S nvidia-smi -lgc 675
echo $pw | sudo -S nvidia-smi -lgc 660
echo $pw | sudo -S nvidia-smi -lgc 645
echo $pw | sudo -S nvidia-smi -lgc 630
echo $pw | sudo -S nvidia-smi -lgc 615
echo $pw | sudo -S nvidia-smi -lgc 600
echo $pw | sudo -S nvidia-smi -lgc 585
echo $pw | sudo -S nvidia-smi -lgc 570
echo $pw | sudo -S nvidia-smi -lgc 555
echo $pw | sudo -S nvidia-smi -lgc 540
echo $pw | sudo -S nvidia-smi -lgc 525
echo $pw | sudo -S nvidia-smi -lgc 510
echo $pw | sudo -S nvidia-smi -lgc 495
echo $pw | sudo -S nvidia-smi -lgc 480
echo $pw | sudo -S nvidia-smi -lgc 465
echo $pw | sudo -S nvidia-smi -lgc 450
echo $pw | sudo -S nvidia-smi -lgc 435
echo $pw | sudo -S nvidia-smi -lgc 420
echo $pw | sudo -S nvidia-smi -lgc 405
echo $pw | sudo -S nvidia-smi -lgc 390
echo $pw | sudo -S nvidia-smi -lgc 375
echo $pw | sudo -S nvidia-smi -lgc 360
echo $pw | sudo -S nvidia-smi -lgc 345
echo $pw | sudo -S nvidia-smi -lgc 330
echo $pw | sudo -S nvidia-smi -lgc 315
echo $pw | sudo -S nvidia-smi -lgc 300